app/blueprints/open/__init__.py
from flask import Blueprint, render_template, request, flash, redirect, url_for

from app.controllers.user_controller import create_user, verify_user, get_user_by_email, signin_user

bp_open = Blueprint('bp_open', __name__)


@bp_open.get('/')
def index():
    return render_template('index.html')


@bp_open.get("/signup")
def signup_get():
    return render_template("signup.html")


@bp_open.post("/signup")
def signup_post():
    first_name = request.form["first_name"]
    last_name = request.form["last_name"]
    email = request.form["email"]
    password = request.form["password"]
    user = get_user_by_email(email)

    if user is not None:
        flash("Error. An account with this email already exists.")
        return redirect(url_for("bp_open.signup_get"))

    create_user(first_name, last_name, email, password)
    return redirect(url_for("bp_open.signin_get"))


@bp_open.get("/signin")
def signin_get():
    return render_template("signin.html")


@bp_open.post("/signin")
def signin_post():
    email = request.form.get("email")
    password = request.form.get("password")
    if not verify_user(email, password):
        flash("Error signing in. Check your email and password!")
        return redirect(url_for("bp_open.signin_get"))

    signin_user(email)

    return redirect(url_for("bp_open.index"))


@bp_open.get("/style_demo")
def style_demo():
    return render_template("style_demo.html")

app/blueprints/user/__init__.py
import json
from flask import Blueprint, redirect, url_for, render_template, request
from flask_login import logout_user, current_user

from app.controllers import user_controller as uc
from app.controllers import schedule_controller as sc


bp_user = Blueprint("bp_user", __name__)


@bp_user.before_request
def before_request():
    if not current_user.is_authenticated:
        return redirect(url_for('bp_open.index'))


@bp_user.get("/signout")
def signout_get():
    logout_user()
    return redirect(url_for("bp_open.index"))


@bp_user.get("/profile")
def profile_get():
    return render_template("profile.html")


@bp_user.post("/profile")
def profile_post():
    first_name = request.form.get("first_name")
    last_name = request.form.get("last_name")
    email = request.form.get("email")
    uc.edit_user(first_name, last_name, email)
    return redirect(url_for("bp_user.profile_get"))


@bp_user.get("/create_schedule/step1")
def schedules_get():
    return render_template("create_schedule_step_1.html")


@bp_user.get("/create_schedule/step2")
def select_disciplines_get():
    disciplines = ["Alpine Skiing", "Biathlon", "Bobsleigh", "Cross-Country Skiing", "Curling", "Figure Skating",
                   "Freestyle Skiing", "Ice Hockey", "Luge", "Nordic Combined", "Short Track Speed Skating", "Skeleton",
                   "Ski Jumping", "Snowboard", "Speed Skating"]
    return render_template("create_schedule_step_2.html", disciplines=disciplines)


@bp_user.post("/create_schedule/step2")
def select_disciplines_post():
    disciplines = ["Alpine Skiing", "Biathlon", "Bobsleigh", "Cross-Country Skiing", "Curling", "Figure Skating",
                   "Freestyle Skiing", "Ice Hockey", "Luge", "Nordic Combined", "Short Track Speed Skating", "Skeleton",
                   "Ski Jumping", "Snowboard", "Speed Skating"]
    chosen = []
    for discipline in request.form:
        if discipline in disciplines:
            chosen.append(discipline)
    print()
    email = current_user.email
    schedule_name = uc.add_step2(email, chosen)

    return redirect(url_for('bp_user.select_countries_get', schedule_name=schedule_name))


@bp_user.get("/create_schedule/step3")
def select_countries_get():
    schedule_name = request.args['schedule_name']
    return render_template("create_schedule_step_3.html", schedule_name=schedule_name)


@bp_user.post("/create_schedule/step3")
def select_countries_post():
    email = current_user.email
    the_list = request.form["theList"]
    schedule_name = request.form['schedule_name']
    countries = json.loads(the_list)
    uc.add_step3(email, schedule_name, countries)
    return redirect(url_for("bp_user.filtered_schedule_get"))


@bp_user.get("/create_schedule/step4")
def filtered_schedule_get():
    schedules, personal_schedules = sc.create_all_schedules()
    shown_date = sc.set_shown_date()
    return render_template("create_schedule_step_4.html", schedules=schedules, personal_schedules=personal_schedules,
                           shown_date=shown_date)


@bp_user.post("/create_schedule/step4")
def step4_post():
    schedules, personal_schedules = sc.create_all_schedules()
    date_action = request.form.get("date_action")
    shown_date = request.form.get("shown_date")
    new_shown_date = sc.set_shown_date(shown_date, date_action)
    schedule_to_save = request.form.get("schedule_to_save")
    uc.save_personal_schedule(schedule_to_save)
    return render_template("create_schedule_step_4.html", schedules=schedules, personal_schedules=personal_schedules,
                           shown_date=new_shown_date)


@bp_user.get("/my_schedule")
def my_schedules_get():
    # _, personal_schedule = create_all_schedules()  # Should be replaced by function to get a personal schedule from the database
    personal_schedule = uc.get_saved_schedule()
    shown_date = sc.set_shown_date()
    return render_template("my_schedule.html", personal_schedule=personal_schedule, shown_date=shown_date)


@bp_user.post("/my_schedule/")
def my_schedules_post():
    # _, personal_schedule = sc.create_all_schedules()  # Should be replaced by function to get a personal schedule from the database
    schedule_name = request.form.get("schedule_name")
    personal_schedule = uc.get_saved_schedule(schedule_name)
    date_action = request.form.get("date_action")
    shown_date = request.form.get("shown_date")
    new_shown_date = sc.set_shown_date(shown_date, date_action)
    return render_template("my_schedule.html", personal_schedule=personal_schedule, shown_date=new_shown_date)

app/templates/base_template.html
<!DOCTYPE html>
<html lang="en">
<head>
<!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<!-- Our stylesheets -->
    <link rel="stylesheet" type="text/css" href="{{ url_for("static", filename='css/base_style.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/event_style.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/step2.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/step3.css') }}">

    <title>The Olympic Planner</title>

    <script type="text/javascript" src="{{ url_for('static', filename='js/functions.js') }}"></script>
    {% block head %}{% endblock %}
</head>

<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container-fluid">
          <a class="navbar-brand mr-4" href="/">The Olympic Planner</a>
        <!-- This button becomes visible when you use a small screen. -->
        <!-- Then the menu options will show as a dropdown from a button instead of a navigation bar. -->
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                      aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

        <!-- Navigation tabs -->
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
                {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="{{ url_for('bp_user.schedules_get') }}">Create Schedule</a>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="{{ url_for('bp_user.my_schedules_get') }}"
                           id="navbardrop" data-toggle="dropdown">My Schedules</a>
                            <div class="dropdown-menu">
                                <form action="{{ url_for("bp_user.my_schedules_post") }}" method="POST">
                                {% for schedule in current_user.schedules %}
                                    <a><input type="submit" class="dropdown-item" name="schedule_name" value="{{ schedule.schedule_name }}"/></a>
                                {% endfor %}
                                    <input type="hidden" name="shown_date" value="{{ shown_date }}"/>
                                </form>
                            </div>
                    </li>
                    <a class="nav-item nav-link ml-auto" href="{{ url_for('bp_user.signout_get') }}">Sign Out</a>
                {% else %}
                    <a class="nav-item nav-link" href="{{ url_for("bp_open.signup_get") }}">Sign Up</a>
                    <a class="nav-item nav-link" href="{{ url_for("bp_open.signin_get") }}">Sign In</a>
                {% endif %}
            </div>

            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                   <a class="nav-item nav-link" href="{{ url_for("bp_user.profile_get") }}">
                        <img src="{{ current_user.avatar }}" alt="My profile" class="avatar">
                   </a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container-fluid" style="max-height: 85vh">
        <div class="row" style="max-height: inherit">
            <div class="col-md-12" style="max-height: inherit">
              {% block content12 %}{% endblock %}
              <div class="row" style="max-height: inherit">
                <div class="col-md-2" style="max-height: inherit">
                  {% block content2l %}{% endblock %}
                </div>
                <div class="col-md-8" style="max-height: inherit">
                  {% block content8 %}{% endblock %}
                </div>
                <div class="col-md-2" style="max-height: inherit">
                  {% block content2r %}{% endblock %}
                </div>
              </div>
            </div>
        </div>
    </main>


    {% block scripts %}
    {% endblock %}
    <!-- Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

app/templates/create_schedule_start.html
{% extends "base_template.html" %}
{% set active_page = "schedules" %}

{%  block content %}
    <div class="content-section">
        <h1>Welcome {{ current_user.first_name }}!</h1>
            <div class="container-fluid">
                <p>Congratulations on your excellent decision to use The Olympic Planner! Click next to create a new schedule, or open an existing one.</p>
            </div>
    </div>
 {% endblock %}

app/templates/create_schedule_step_2.html
{% extends "base_template.html" %}

{% block content8 %}
    <div class="content-section overflow-auto" style="max-height: inherit">

        <h3>Please select the disciplines of interest!</h3>
        <p>Hint: Leave all checkboxes blank to get all disciplines.</p>

        <form id="disciplines" action="{{url_for("bp_user.select_disciplines_post")}}" method="POST">
            {% for discipline in disciplines %}
                <div class="checkbox-container">
                    <input type="checkbox" id="d{{ loop.index }}" name="{{ discipline }}" value="{{ discipline }}">
                    <label for="d{{ loop.index }}">{{ discipline }}</label>
                </div>
            {% endfor %}

            <div>
                <input name="hiddenList" type="hidden" id="isHidden" />
                <input type="submit" class="btn btn-primary" onclick="sendIt()" value="Select And Go To Next Step">
            </div>
        </form>
    </div>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js">

let chosenDisciplines = [];
document.getElementById("disciplines").onsubmit = () => {
    document.getElementById("isHidden").checked = JSON.stringify(chosenDisciplines)
}
function isChecked() {
    let discipline = document.forms[0];
    let discipline_array = [];
    for (let i = 0; i < discipline.length; i++) {
        if (discipline[i].checked) {
            discipline_array.push(discipline[i].value);
        }
    }
}


function sendIt() {
    let chosenForm = document.getElementById("disciplines");
    chosenForm.submit();
}
</script>



{% endblock %}

app/templates/create_schedule_step_4.html
{% extends "base_template.html" %}
{% set active_page = "schedules" %}

{%  block content12 %}
    <div class="content-section" style="max-height: inherit">
        <div class="container-fluid">
            <h3>Olympic Schedule</h3>
            <p> Click on events to move them to your personal schedule on the right. </p>
        </div>
        <div class="row">
        <div class="container col-md-7">
            <form class="col-md-7 d-flex justify-content-left my-4" action="{{ url_for("bp_user.step4_post") }}" method="POST">
                <div class="btn-group" role="group" aria-label="Change date-buttons">
                    <input type="submit" class="form-control mr-2" name="date_action" value="Today"/> <br/>
                    <input type="submit" class="form-control mr-2" name="date_action" value="First day"/> <br/>
                    <input type="submit" class="form-control mr-2" name="date_action" value="Previous"/> <br/>
                    <input type="submit" class="form-control btn-info mr-2" name="date_action" value=" Showing: {{ shown_date }}"/> <br/>
                    <input type="submit" class="form-control mr-2" name="date_action" value="Next"/> <br/>
                    <input type="submit" class="form-control mr-2" name="date_action" value="Last day"/> <br/>
                    <input type="hidden" name="shown_date" value="{{ shown_date }}"/>
                </div>
            </form>
        </div>
        <div class="container col-md-4">
            <form class="col-md-3 float-left d-flex justify-content-right my-4" action="{{ url_for("bp_user.step4_post") }}" method="POST">
                <div class="btn-group" role="group" aria-label="Change date-buttons">
                    <input type="submit" class="btn btn-primary" value="Save this schedule">
                    <input type="hidden" name="schedule_to_save" value="{{ personal_schedules }}">
                    <input type="hidden" name="shown_date" value="{{ shown_date }}"/>
                </div>
            </form>
        </div>
        </div>
        <div class="container-fluid overflow-auto" style="max-height: 78%">
            <div class="row">
                <div class="container col-md-7 overflow-auto">
                    {% for schedule in schedules %}
                        {% if shown_date in schedule[0] %}
                            <div class="base-schedule" id="base-schedule{{ loop.index }}">
                                {{ schedule[1] | safe }}
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="container col-md-4 overflow-auto">
                    {% for personal_schedule in personal_schedules %}
                        {% if shown_date in personal_schedule[0] %}
                                <div class="personal-schedule" id="personal-schedule{{ loop.index }}">
                                    {{ personal_schedule[1] | safe }}
                                </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
            <div class="container">
            </div>
    </div>
{% endblock %}


{% block scripts %}
<script>
    //Get all clone-me-td's and add moveIt() on click
    const clonableTds = document.querySelectorAll(".clone-me");
    clonableTds.forEach(div => {
        div.addEventListener("click", moveIt);
    });

    //Create boolean array of arrays-table for keeping track of which cells that are available (=true)
    let emptyTimeSlots = [[false, false, false, false, false, false]];
    for (let i = 1; i < 63; i++) {
        let defaultRow = [false, true, true, true, true, true];
        emptyTimeSlots.push(defaultRow);
    }

    //Variable for picking up all divs with a certain class in personal schedule
    let events;

    //Function for moving the div from base schedule to personal schedule
    function moveIt(e) {
        // Get the div that we clicked
        let targetDiv = e.path[1];
        // Get the cell hosting the div in the from table
        let targetCell = targetDiv.parentElement;
        // Get the id of the row containing the div
        let parentRowId = e.path[3].rowIndex;
        //Get the target table id
        let targetTableId = e.path[5].id;
        // Get the id of the row in the destination table
        let destinationRowId = parentRowId;
        // Get the current cells rowspan
        let rowspan = targetCell.rowSpan;
        // Get the destination table using using target table id
        let targetTableIdWithoutType = targetTableId.substring(1);
        let toTable = document.getElementById("p" + targetTableIdWithoutType);
        // Remove the div from the original table
        targetDiv.parentElement.removeChild(targetDiv);

        //Look for available time slots from priority column 1 through 5
        let lastEmptyTimeSlotRow = null;
        let lastEmptyTimeSlotColumn = null;
        let available = false;
        let column = 0;
        for (let i = 1; i < emptyTimeSlots[0].length; i++) {
            column++;
            if (emptyTimeSlots[parentRowId][column] === true) {
                lastEmptyTimeSlotRow = parentRowId;
                for (let j = 1; j < rowspan; j++) {
                    lastEmptyTimeSlotRow++;
                    if (emptyTimeSlots[lastEmptyTimeSlotRow][column] === true) {
                        lastEmptyTimeSlotColumn = column;
                        if (j === rowspan - 1) {
                            available = true;
                        }
                    }
                }
            }
            if (available === true) {
                break;
            }
        }

        //Add div to the first available priority column, checked in emptyTimeSlots
        toTable.rows[parentRowId].cells[lastEmptyTimeSlotColumn].appendChild(targetDiv);
        toTable.rows[parentRowId].cells[lastEmptyTimeSlotColumn].rowSpan = rowspan;
        targetDiv.classList.remove("clone-me");
        targetDiv.classList.add("click-me");

        //Update emptyTimeSlots for the cells the div occupy
        for (let i = rowspan; i > 0; i--) {
            emptyTimeSlots[lastEmptyTimeSlotRow][lastEmptyTimeSlotColumn] = false;
            lastEmptyTimeSlotRow--;
        }

        //Remove old event listener
        let targetDivId = targetDiv.id;
        document.getElementById(targetDivId).removeEventListener("click", moveIt);

        // Add new event listeners for all
        events = document.getElementsByClassName("click-me");

        // Attach the event listeners for the click event on all divs
        for (let i = 0; i < events.length; i++) {
            events[i].addEventListener("click", clickEvent, false);
        }



        //Remove added td's because of rowspan
        let tbody = toTable.childNodes[0];
        for (let i = 1; i < rowspan; i++) {
            let currentRow = tbody.childNodes[parentRowId + i];
            currentRow.deleteCell(-1);
        }
    }

    function clickEvent(e) {
        // Get the div, td, row and table
        let currentDiv = e.path[1];
        let currentTd = e.path[2];
        let currentRow = e.path[3];
        let rowspan = currentTd.rowSpan;
        let currentTable = e.path[5];

        // Calculate the start and end row for the clicked event
        let clickedStartRowId = currentRow.rowIndex;
        let clickedEndRow = currentTd.rowSpan + clickedStartRowId - 1;


        // Get the row(s) for the div in an array and then generate a set of the array
        let sequenceClicked = [];
        for (let i = clickedStartRowId; i <= clickedEndRow; i++) {
            sequenceClicked.push(i);
        }
        let clickedColumn = new Set(sequenceClicked);


        // Get the rows for the checked column until clickedEndRow and store it in a set
        for (let col = 1; col < 6; col++) {
            let sequenceChecked = [];
            for (let row = 1; row <= clickedEndRow; row++) {
                if(emptyTimeSlots[row][col] === false) {
                    // If we need to check if the current event is the clicked
                    // But do we want that???
                    if(emptyTimeSlots[row][col] === currentDiv) {
                     }
                    sequenceChecked.push(row);
                }
            }
            let checkedColumn = new Set(sequenceChecked);
            // If we have an intersection we can't place the selected event in
            // this column
            if(intersection(clickedColumn, checkedColumn).size > 0) {
            }
            else {
                // But here we can. Yay!!!!
                currentTable.rows[clickedStartRowId].cells[col].appendChild(currentDiv);
                currentTable.rows[clickedStartRowId].cells[col].rowSpan = rowspan;
                // toTable.rows[parentRowId].cells[lastEmptyTimeSlotColumn].appendChild(targetDiv);
                // toTable.rows[parentRowId].cells[lastEmptyTimeSlotColumn].rowSpan = rowspan;
                break;
            }
        }
    }

    // Function to check set intersections (the same td in two rowspan)
    function intersection(setA, setB) {
        let _intersection = new Set()
        for (let elem of setB) {
            if (setA.has(elem)) {
                _intersection.add(elem)
            }
        }
        return _intersection
    }

    // Function to check if a cell in the table is empty
    function elementIsEmpty(el) {
        return (/^(\s|&nbsp;)*$/.test(el.innerHTML));
    }
</script>

{% endblock %}

app/templates/index.html
{% extends "base_template.html" %}

{%  block content8 %}
    <h1 class="display-1">The Olympic Planner</h1><br>
    <h2>An app to make your olympic weeks run smoothly</h2>
{% endblock %}

app/templates/my_schedule.html
{% extends "base_template.html" %}
{% set active_page = "/user/my_schedule" %}

{%  block content8 %}
    <div class="content-section" style="max-height: inherit">
         <div class="container-fluid">
            <h1>{{ current_user.first_name }}'s personal schedule for {{ shown_date }}</h1>
             <p>Current schedule: {{ personal_schedule["schedule_name"] }}</p>
         </div>
        <div class="container-fluid">
            <form class="col-md-12 d-flex justify-content-left my-4" action="{{ url_for("bp_user.my_schedules_post") }}" method="POST">
                <div class="btn-group" role="group" aria-label="Change date-buttons">
                    <input type="submit" class="form-control mr-2" name="date_action" value="Today"/> <br/>
                    <input type="submit" class="form-control mr-2" name="date_action" value="First day"/> <br/>
                    <input type="submit" class="form-control mr-2" name="date_action" value="Previous"/> <br/>
                    <input type="submit" class="form-control btn-info mr-2" name="date_action"
                           value=" Showing: {{ shown_date }}"/> <br/>
                    <input type="submit" class="form-control mr-2" name="date_action" value="Next"/> <br/>
                    <input type="submit" class="form-control mr-2" name="date_action" value="Last day"/> <br/>
                    <input type="hidden" name="shown_date" value="{{ shown_date }}"/>
                </div>
            </form>
        </div>
        <div class="container-fluid overflow-auto" style="max-height: 78%">
            {% for day_schedule in personal_schedule %}
                {% if shown_date in day_schedule[0] %}
                    <div class="personal-schedule">
                        {{ day_schedule[1] | safe }}
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>

    </script>

{% endblock %}

app/templates/schedule_start.html
{% extends "base_template.html" %}
{% set active_page = "schedules" %}

{%  block content %}
    <div class="content-section">
        <h1>Welcome {{ current_user.first_name }}!</h1>
            <div class="container-fluid">
                <p>Congratulations on your excellent decision to use The Olympic Planner! Click next to create a new schedule, or open an existing one.</p>
            </div>
    </div>
 {% endblock %}

app/templates/signin.html
{%  extends "base_template.html" %}
{% set active_page = "signin" %}

{% block content8 %}
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <div class="notification">
                        {{ message }}
                    </div>
                {%  endfor %}
            {% endif %}
        {%  endwith %}
        <form class="col-md-4" action="{{ url_for("bp_open.signin_post") }}" method="POST">
            <input type="email" class="form-control" placeholder="Email Address" name="email"/> <br/>
            <input type="password" class="form-control" placeholder="Password" name="password"/> <br/>
            <input type="submit" class="btn btn-primary" value="Sign in!"/>
        </form>
{% endblock %}

app/templates/signup.html
{%  extends "base_template.html" %}

{% block content8 %}
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <div class="notification">
                        {{ message }}
                    </div>
                {%  endfor %}
            {% endif %}
        {%  endwith %}
        <form class="col-md-4" action="{{ url_for("bp_open.signup_post") }}" method="POST">
            <input type="text" class="form-control" placeholder="First Name" name="first_name"/> <br/>
            <input type="text" class="form-control" placeholder="Last Name" name="last_name"/> <br/>
            <input type="email" class="form-control" placeholder="Email Address" name="email"/> <br/>
            <input type="password" class="form-control" id="pwd1" oninput="verifyPassword()" placeholder="Password" name="password"/>
            <span id="pwd-message"></span><br/>
            <input type="password" class="form-control" id="pwd2" oninput="checkPassword()" placeholder="Repeat Password" disabled/> <br/>
            <input type="submit" class="btn btn-primary" id="submit" value="Sign up!" disabled/>
        </form>
{% endblock %}

{% block scripts %}
    <script>
        function checkPassword() {
            let pwd1 = document.getElementById("pwd1");
            let pwd2 = document.getElementById("pwd2");
            document.getElementById("submit").disabled = pwd1.value !== pwd2.value;
        }

        function verifyPassword() {
            let pwdInput = document.getElementById("pwd1");
            let pwdMessage = document.getElementById("pwd-message");
            let resultObj = CheckPassword(pwdInput.value);
            pwdMessage.innerHTML = resultObj.message;
            document.getElementById("pwd2").disabled = !resultObj.result;
        }

        function CheckPassword(inputText) {
            let pattern = /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[^a-zA-Z0-9])(?!.*\s).{6,1000}$/;
            let obj = {}
            if (inputText.match(pattern)) {
                obj.result = true;
                obj.message = "";
            } else {
                obj.result = false;
                obj.message = "Password must be 6 characters long and contain at least 1 lower case letter, 1 upper " +
                              "case letter, 1 digit, and 1 special character."
            }
            return obj;
        }

    </script>
{% endblock %}